# -*- coding: utf-8 -*-
"""GuessingGame1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VFCjoWzYRkpUJaavUlEIYR8A5tDklTl
"""

import streamlit as st

st.markdown(
    """
    <style>
    .stApp {
        background-image: url("https://pin.it/3EmaUtxRI");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.set_page_config(page_title="هل اللعبة تقدر تخمن رقمك؟🤖", page_icon="🎯", layout="centered")


st.markdown("""
    <style>
    .main {
        background-color: #f0f6ff;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 0 15px rgba(0,0,0,0.1);
    }
    .stButton>button {
        font-size: 18px;
        padding: 0.5em 1em;
        border-radius: 10px;
        margin: 0.2em;
        background-color: #4682B4;
        color: white;
        border: none;
        transition: all 0.3s ease-in-out;
    }
    .stButton>button:hover {
        background-color: #5b9bd5;
        transform: scale(1.05);
    }
    </style>
""", unsafe_allow_html=True)


st.title("💙 Guessing Game 🤖")

st.markdown("### اختر رقمًا بين **1 و100** في ذهنك، وسأحاول تخمينه🤖")


if st.button("🎮 ابدأ اللعبة"):
    st.session_state["start"] = True
    st.session_state["low"] = 1
    st.session_state["high"] = 100
    st.session_state["step"] = 0


if "start" in st.session_state and st.session_state["start"]:
    if "mid" not in st.session_state or st.button("➡️ التالي"):
        st.session_state["mid"] = (st.session_state["low"] + st.session_state["high"]) // 2
        st.session_state["step"] += 1

    st.subheader(f"🤔 هل الرقم هو **{st.session_state['mid']}**؟")

    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("📉 أصغر"):
            st.session_state["high"] = st.session_state["mid"] - 1
    with col2:
        if st.button("✅ صحيح!"):
            st.success(f"🎉 وجدته! الرقم هو **{st.session_state['mid']}** بعد {st.session_state['step']} محاولة 👏")
            st.session_state["start"] = False
    with col3:
        if st.button("📈 أكبر"):
            st.session_state["low"] = st.session_state["mid"] + 1